export const pontos = [
  {
    "id_ponto": 1,
    "nome": "Ana Rosa",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 14,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-10-27",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.582095, -46.638249",
    "endereco_completo": "Rua Vergueiro , São Paulo - 04102000",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": true,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": "Visão de rua parcial",
    "linha_metro": "L1 - Azul|#0E539E;L2 - Verde|#217F62",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 2,
    "nome": "Armênia",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 2,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2022-01-05",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.525384, -46.630176",
    "endereco_completo": "Avenida do Estado , São Paulo - 01102040",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L1 - Azul|#0E539E",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 3,
    "nome": "Artur Alvim",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 17,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-19",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.540314, -46.483469",
    "endereco_completo": "Rua Boipeva , São Paulo - 08220030",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 4,
    "nome": "Brás",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 10,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-19",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.547266, -46.615807",
    "endereco_completo": "Rua Domingos Paiva 436, São Paulo - 03043070",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": "L13 - Jade|#2FA961",
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 5,
    "nome": "Carrão",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 40,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-01",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.538509, -46.563569",
    "endereco_completo": "Rua Melo Freire , São Paulo - 03314030",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 6,
    "nome": "Parada Inglesa",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 8,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-19",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.486822, -46.608286",
    "endereco_completo": "Rua Manuel Taveira , São Paulo - 02242005",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": true,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": "Visão de rua parcial",
    "linha_metro": "L1 - Azul|#0E539E",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 7,
    "nome": "Patriarca",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 10,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-18",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.530040, -46.501008",
    "endereco_completo": "Rua São Serapião Rua São Serapião, São Paulo - 05212160",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 8,
    "nome": "Penha",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 24,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-18",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.518716, -46.546889",
    "endereco_completo": "Avenida Gabriela Mistral Avenida Gabriela Mistral, São Paulo - 03701000",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 9,
    "nome": "Santana",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 32,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-01",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.502689, -46.623818",
    "endereco_completo": "Rua Ezequiel Freire , São Paulo - 02034001",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L1 - Azul|#0E539E",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 10,
    "nome": "Tatuapé",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 31,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-10-27",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.539660, -46.576796",
    "endereco_completo": "Rua Catiguá , São Paulo - 03065030",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": "L11 - Coral|#EA562F;L12 - Safira|#0E3E86",
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 11,
    "nome": "Vila Matilde",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 12,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2021-11-15",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.531168, -46.529739",
    "endereco_completo": "Rua Alvinópolis , São Paulo - 03644070",
    "nome_concedente": "Unitah",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 12,
    "nome": "Catarina",
    "categoria": "Shopping",
    "praca": "São Paulo",
    "qtd_faces": 24,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "1.8707",
    "data_venda_inicio": "2023-10-10",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "09:00:00 - 23:00:00",
    "lat_long": "-23.419968, -47.163200",
    "endereco_completo": "Rua Rafael Costa Dias 140, São Roque - 18147000",
    "nome_concedente": "Shopping Catarina",
    "is_emtu": null,
    "is_ponto_final": null,
    "is_ponto_passagem": null,
    "is_ponto_inicial": null,
    "is_sptrans": null,
    "is_visao_rua": null,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": true,
    "contem_wifi": null
  },
  {
    "id_ponto": 13,
    "nome": "Amaral Gurgel",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 2,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-11-17",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.540665, -46.647458",
    "endereco_completo": "Rua Dr. Frederico Steidel 107, São Paulo - 01225030",
    "nome_concedente": "Socicam",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": false,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": "L3 - Vermelha|#E7483C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 14,
    "nome": "Campo Limpo",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 22,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2022-12-31",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.631107, -46.772854",
    "endereco_completo": "Estrada do Campo Limpo , São Paulo - 05788250",
    "nome_concedente": "Socicam",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 15,
    "nome": "Casa Verde",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 3,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2024-09-14",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.496153, -46.662431",
    "endereco_completo": "Rua Baía Formosa 80, São Paulo - 02552120",
    "nome_concedente": "Socicam",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 16,
    "nome": "Lapa",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 24,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2022-11-28",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.520171, -46.699973",
    "endereco_completo": "Praça Miguel Dell'Erba 50, São Paulo - 05033060",
    "nome_concedente": "Socicam",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": "L7 - Rubi|#9A2165",
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 17,
    "nome": "Pinheiros",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 38,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-01-28",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.566361, -46.701710",
    "endereco_completo": "Rua Gilberto Sabino Rua Gilberto Sabino, São Paulo - 05425020",
    "nome_concedente": "Socicam",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": "L4 - Amarela|#FFE020",
    "linha_trem": "L9 - Esmeralda|#2CA58F",
    "is_alterado": true,
    "contem_wifi": true
  },
  {
    "id_ponto": 18,
    "nome": "Pirituba",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 18,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-01-21",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.486195, -46.726310",
    "endereco_completo": "Avenida Doutor Felipe Pinel , São Paulo - 02939000",
    "nome_concedente": "Socicam",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 19,
    "nome": "Princesa Isabel",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 2,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2024-09-23",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.534286, -46.644776",
    "endereco_completo": "Alameda Glete 433, São Paulo - 01215000",
    "nome_concedente": "Socicam",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 21,
    "nome": "Raposo",
    "categoria": "Shopping",
    "praca": "São Paulo",
    "qtd_faces": 10,
    "qtd_segundos_loop": 120,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 12,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2022-01-31",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "07:00:00 - 23:00:00",
    "lat_long": "-23.587600, -46.751023",
    "endereco_completo": "Rodovia Raposo Tavares , São Paulo - 05577200",
    "nome_concedente": "Shopping Raposo",
    "is_emtu": null,
    "is_ponto_final": null,
    "is_ponto_passagem": null,
    "is_ponto_inicial": null,
    "is_sptrans": null,
    "is_visao_rua": null,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 22,
    "nome": "Camaragibe",
    "categoria": "Terminal de ônibus",
    "praca": "Recife",
    "qtd_faces": 8,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-10",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-8.024894, -34.995877",
    "endereco_completo": "Avenida Doutor Belmino Correia Avenida Doutor Belmino Correia, Camaragibe - 54762235",
    "nome_concedente": "Nova Mobi",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "Linha Centro - 2|#FD6F00",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 23,
    "nome": "Caxangá",
    "categoria": "Terminal de ônibus",
    "praca": "Recife",
    "qtd_faces": 4,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-01-26",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-8.031291, -34.954943",
    "endereco_completo": "Pr. do Caxangá , Recife - 50800270",
    "nome_concedente": "Nova Mobi",
    "is_emtu": null,
    "is_ponto_final": null,
    "is_ponto_passagem": null,
    "is_ponto_inicial": null,
    "is_sptrans": null,
    "is_visao_rua": null,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 24,
    "nome": "Joana Bezerra",
    "categoria": "Terminal de ônibus",
    "praca": "Recife",
    "qtd_faces": 8,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-01-21",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-8.072178, -34.895702",
    "endereco_completo": "Avenida Central , Recife - 50030230",
    "nome_concedente": "Nova Mobi",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "Linha Sul|#0000FE;Linha Centro - 1|#FF0007;Linha Centro - 2|#FD6F00",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 25,
    "nome": "PE-15",
    "categoria": "Terminal de ônibus",
    "praca": "Recife",
    "qtd_faces": 6,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-01-31",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-7.982505, -34.856626",
    "endereco_completo": "Rodovia PE-15 , Olinda - 53020560",
    "nome_concedente": "Nova Mobi",
    "is_emtu": null,
    "is_ponto_final": null,
    "is_ponto_passagem": null,
    "is_ponto_inicial": null,
    "is_sptrans": null,
    "is_visao_rua": null,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 26,
    "nome": "Pelópidas Silveira",
    "categoria": "Terminal de ônibus",
    "praca": "Recife",
    "qtd_faces": 12,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-06",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-7.947255, -34.877861",
    "endereco_completo": "Rodovia PE-15 , Paulista - 53401445",
    "nome_concedente": "Nova Mobi",
    "is_emtu": null,
    "is_ponto_final": null,
    "is_ponto_passagem": null,
    "is_ponto_inicial": null,
    "is_sptrans": null,
    "is_visao_rua": null,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 27,
    "nome": "Tancredo Neves",
    "categoria": "Terminal de ônibus",
    "praca": "Recife",
    "qtd_faces": 8,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-17",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-8.121798, -34.912312",
    "endereco_completo": "Avenida Sul Gov. Cid Sampaio 321, Recife - 50090010",
    "nome_concedente": "Nova Mobi",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": false,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": "Linha Sul|#0000FE",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 28,
    "nome": "Xambá",
    "categoria": "Terminal de ônibus",
    "praca": "Recife",
    "qtd_faces": 8,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-01-30",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-8.001340, -34.892817",
    "endereco_completo": "Avenida Presidente Kennedy , Olinda - 53270735",
    "nome_concedente": "Nova Mobi",
    "is_emtu": null,
    "is_ponto_final": null,
    "is_ponto_passagem": null,
    "is_ponto_inicial": null,
    "is_sptrans": null,
    "is_visao_rua": null,
    "administracao": null,
    "ponto_metro": null,
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 29,
    "nome": "Água Espraiada",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 4,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-03-10",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.613700, -46.695233",
    "endereco_completo": "Avenida Jornalista Roberto Marinho 700, São Paulo - 04576010",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": true,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": "Visão de rua total",
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 30,
    "nome": "Bandeira",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 30,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2024-11-07",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.549514, -46.639573",
    "endereco_completo": "Praça da Bandeira , São Paulo - 01313000",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": false,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": true,
    "contem_wifi": true
  },
  {
    "id_ponto": 31,
    "nome": "Capelinha",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 28,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-10",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.654222, -46.762389",
    "endereco_completo": "Estrada de Itapecerica 3222, São Paulo - 05835005",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 32,
    "nome": "Grajaú",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 28,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-27",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.736938, -46.697166",
    "endereco_completo": "Rua Giovanni Bononcini 77, São Paulo - 04843020",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": "L9 - Esmeralda|#2CA58F",
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 33,
    "nome": "Guarapiranga",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 12,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-11",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.668138, -46.735390",
    "endereco_completo": "Estrada do M'Boi Mirim 150, São Paulo - 04905000",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 34,
    "nome": "Jardim Ângela",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 10,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-04-11",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.690633, -46.774062",
    "endereco_completo": "Estrada do M'Boi Mirim 4901, São Paulo - 04939003",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 35,
    "nome": "João Dias",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 26,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-10",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.643740, -46.733768",
    "endereco_completo": "Avenida João Dias 3589, São Paulo - 05801110",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": true,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": "Visão de rua parcial;Visão de rua total",
    "linha_metro": "L5 - Lilás|#76509C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 36,
    "nome": "Parelheiros",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 4,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-02-24",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.828302, -46.727123",
    "endereco_completo": "Estrada da Colonia Mário Reimberg Christe , São Paulo - 08370190",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 37,
    "nome": "Santo Amaro",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 30,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-01-21",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.654187, -46.711432",
    "endereco_completo": "Avenida Padre José Maria 430, São Paulo - 04753060",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": "L5 - Lilás|#76509C",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 38,
    "nome": "Varginha",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 28,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-03-08",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.766906, -46.716321",
    "endereco_completo": "Avenida Paulo Guilguer Reimberg , São Paulo - 04858570",
    "nome_concedente": "Egypt",
    "is_emtu": false,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": true
  },
  {
    "id_ponto": 39,
    "nome": "Diadema",
    "categoria": "Terminal de ônibus",
    "praca": "ABD",
    "qtd_faces": 16,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-05-04",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.684401, -46.626569",
    "endereco_completo": "Avenida Conceição , Diadema - 09920000",
    "nome_concedente": "Next Mobilidade",
    "is_emtu": true,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": "EMTU",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 40,
    "nome": "Ferrazópolis",
    "categoria": "Terminal de ônibus",
    "praca": "ABD",
    "qtd_faces": 4,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-05-10",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.720556, -46.551058",
    "endereco_completo": "Avenida Brigadeiro Faria Lima , São Bernardo do Campo - 09720010",
    "nome_concedente": "Next Mobilidade",
    "is_emtu": true,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": "EMTU",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 41,
    "nome": "Jabaquara",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 24,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-04-07",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.646737, -46.639546",
    "endereco_completo": "Rua Nelson Fernandes Rua Nelson Fernandes, São Paulo - 04320030",
    "nome_concedente": "Next Mobilidade",
    "is_emtu": true,
    "is_ponto_final": true,
    "is_ponto_passagem": false,
    "is_ponto_inicial": true,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": "EMTU",
    "ponto_metro": "Ponto inicial;Ponto final",
    "visao_rua": null,
    "linha_metro": "L1 - Azul|#0E539E",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 42,
    "nome": "Piraporinha",
    "categoria": "Terminal de ônibus",
    "praca": "ABD",
    "qtd_faces": 12,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-05-09",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.691676, -46.585051",
    "endereco_completo": "Avenida Piraporinha , Diadema - 09950000",
    "nome_concedente": "Next Mobilidade",
    "is_emtu": true,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": "EMTU",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 43,
    "nome": "Santo André",
    "categoria": "Terminal de ônibus",
    "praca": "ABD",
    "qtd_faces": 20,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-05-17",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.652786, -46.528976",
    "endereco_completo": "Avenida XV de novembro , Santo André - 09015000",
    "nome_concedente": "Next Mobilidade",
    "is_emtu": true,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": "EMTU",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 44,
    "nome": "São Bernardo",
    "categoria": "Terminal de ônibus",
    "praca": "ABD",
    "qtd_faces": 4,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-05-10",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.698285, -46.552235",
    "endereco_completo": "Praça Samuel Sabatini , São Bernardo do Campo - 09710002",
    "nome_concedente": "Next Mobilidade",
    "is_emtu": false,
    "is_ponto_final": false,
    "is_ponto_passagem": true,
    "is_ponto_inicial": false,
    "is_sptrans": false,
    "is_visao_rua": false,
    "administracao": null,
    "ponto_metro": "Ponto de passagem",
    "visao_rua": null,
    "linha_metro": null,
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  },
  {
    "id_ponto": 45,
    "nome": "São Mateus",
    "categoria": "Terminal de ônibus",
    "praca": "São Paulo",
    "qtd_faces": 20,
    "qtd_segundos_loop": 150,
    "qtd_segundos_insercao": 10,
    "qtd_slots": 15,
    "preco_insercao": "0.6500",
    "data_venda_inicio": "2023-05-29",
    "largura_x_altura": "256x512",
    "horario_funcionamento": "05:00:00 - 01:00:00",
    "lat_long": "-23.613486, -46.476294",
    "endereco_completo": "Avenida Adélia Chohfi , São Paulo - 08320390",
    "nome_concedente": "Next Mobilidade",
    "is_emtu": true,
    "is_ponto_final": true,
    "is_ponto_passagem": true,
    "is_ponto_inicial": true,
    "is_sptrans": true,
    "is_visao_rua": false,
    "administracao": "EMTU;SPTrans",
    "ponto_metro": "Ponto inicial;Ponto de passagem;Ponto final",
    "visao_rua": null,
    "linha_metro": "L15 - Prata|#868D90",
    "linha_trem": null,
    "is_alterado": false,
    "contem_wifi": null
  }
]